from django.urls import path
from . import views

app_name = 'realise'

urlpatterns = [
    path('',                         views.dashboard,              name='dashboard'),
    path('oih-vs-stock/',            views.oih_vs_stock,           name='oih_vs_stock'),
    path('compare-sales/',           views.compare_sales,          name='compare_sales'),
    path('targets/',                 views.person_targets_page,    name='channel_targets'),
    path('targets/embed/',           views.person_targets_embed,   name='person_targets_embed'),
    path('targets/legacy/',          views.channel_targets_page,   name='channel_targets_legacy'),
    path('channel/<str:group>/',     views.channel_detail_placeholder, name='channel_detail'),
    path('api/health/',              views.api_health,             name='api_health'),
    path('api/sales-data/',          views.api_sales_data,         name='api_sales_data'),
    path('api/beverages-data/',      views.api_beverages_data,     name='api_beverages_data'),
    path('api/beverages-docs/',      views.api_beverages_docs,     name='api_beverages_docs'),
    path('api/channel-targets/',     views.api_channel_targets,    name='api_channel_targets'),
    path('api/segment-targets/',     views.api_segment_targets,    name='api_segment_targets'),
    path('api/order-in-hand/',       views.api_order_in_hand,      name='api_order_in_hand'),
    path('api/order-in-hand-rows/',  views.api_order_in_hand_rows, name='api_order_in_hand_rows'),
    path('api/target-nodes/',        views.api_target_nodes,       name='api_target_nodes'),
    path('api/channel-detail-docs/', views.api_channel_detail_docs, name='api_channel_detail_docs'),
    path('api/commodity-oih-rows/',  views.api_commodity_oih_rows,  name='api_commodity_oih_rows'),
    path('api/oih-breakdown/',       views.api_oih_breakdown,       name='api_oih_breakdown'),
    path('api/drill-down/',          views.api_drill_down,         name='api_drill_down'),
    path('api/historical-realise/',  views.api_historical_realise, name='api_historical_realise'),
    path('api/targets/',             views.api_targets,            name='api_targets'),
    path('api/save-targets/',        views.api_save_targets,       name='api_save_targets'),
    path('api/territory-map/',        views.api_territory_map,       name='api_territory_map'),
    path('api/territory-map/save/',   views.api_save_territory_map,  name='api_save_territory_map'),
    path('api/territory-map/refresh/', views.api_refresh_territory_map, name='api_refresh_territory_map'),
    path('api/territory-targets/',      views.api_territory_targets,      name='api_territory_targets'),
    path('api/territory-targets/save/', views.api_save_territory_targets, name='api_save_territory_targets'),
    path('api/territory-product-targets/',      views.api_territory_product_targets,      name='api_territory_product_targets'),
    path('api/territory-product-targets/save/', views.api_save_territory_product_targets, name='api_save_territory_product_targets'),
    path('api/channel-quick-targets/',      views.api_channel_quick_targets,      name='api_channel_quick_targets'),
    path('api/channel-quick-targets/save/', views.api_save_channel_quick_targets, name='api_save_channel_quick_targets'),
    path('api/product-actuals/',            views.api_product_actuals,            name='api_product_actuals'),
    path('api/verify-pin/',          views.api_verify_pin,         name='api_verify_pin'),
    path('api/export-raw-csv/',      views.api_export_raw_csv,     name='api_export_raw_csv'),
    path('api/export-excel/',        views.api_export_excel,       name='api_export_excel'),
]
