"""Build core/static/vendor/css/lucide.css - the panel's self-hosted Lucide icon set.

Why: the panel must work without internet, so we never link a CDN. This script pulls the
Lucide SVGs once and bakes them into ONE css file as data-URI masks. Each icon becomes a
class, e.g. <i class="ic ic-download"></i>.

The icon is painted with `background-color: currentColor` through a mask, so it takes the
text colour, and it is sized 1em x 1em, so `font-size` sets its size - exactly how the old
Material icon font behaved. That is why the old `.material-icons { font-size: 17px; color: X }`
rules kept working when they were renamed to `.ic`.

To add an icon: put its Lucide name in ICONS below, run this file, commit the new css.

    python deploy/build_lucide_icons.py

Needs internet (jsdelivr) only when you run it. Lucide is ISC-licensed.
"""
import base64
import os
import re
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor

SRC = 'https://cdn.jsdelivr.net/npm/lucide-static@latest/icons/%s.svg'
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'core', 'static', 'vendor', 'css', 'lucide.css')

# Every icon the panel uses. Keep it sorted; drop a name when nothing uses it any more.
ICONS = """
arrow-left arrow-left-right award banknote book-open boxes brain briefcase bus calculator
calendar calendar-check calendar-days chart-column chart-line check check-check chevron-down
chevron-right chevrons-down-up chevrons-up-down circle circle-alert circle-check circle-check-big
circle-x
clipboard-check clipboard-clock clipboard-list cog compass contact-round credit-card cup-soda
database delete download droplet eye eye-off factory file-text flag folder-open gavel git-fork
globe hand hard-hat id-card inbox indian-rupee info landmark layers layout-dashboard list-filter
lock lock-open map-pin menu network package party-popper pencil piggy-bank plus receipt
receipt-indian-rupee receipt-text refresh-cw rocket save scale search settings shield-check
shuffle siren sliders-horizontal snail sparkles store table table-properties tag target trash-2
trending-up triangle-alert trophy truck upload user user-cog user-plus users wallet warehouse
undo-2 wrench x zap
""".split()

BASE_CSS = """/* Lucide icons - self-hosted, generated by deploy/build_lucide_icons.py. DO NOT hand-edit.
   Use:  <i class="ic ic-download"></i>
   Size it with font-size (the icon is 1em), colour it with color (it follows currentColor).
   The paint (background-color) is switched on by the per-icon class, so a wrong or missing
   icon name shows nothing instead of a solid square. */
.ic{display:inline-block;width:1em;height:1em;flex:0 0 auto;font-size:24px;line-height:1;
    vertical-align:-.15em;background-color:transparent;
    -webkit-mask:var(--ic,none) no-repeat center/contain;mask:var(--ic,none) no-repeat center/contain}
"""


def fetch(name):
    with urllib.request.urlopen(SRC % name, timeout=30) as r:
        svg = r.read().decode('utf-8')
    svg = re.sub(r'<!--.*?-->', '', svg, flags=re.S)          # strip the licence comment
    svg = re.sub(r'\s+', ' ', svg).strip()                    # one line
    return name, svg


def main():
    with ThreadPoolExecutor(max_workers=12) as ex:
        got = dict(ex.map(fetch, ICONS))
    missing = [n for n in ICONS if not got.get(n, '').startswith('<svg')]
    if missing:
        sys.exit('could not fetch: %s' % ', '.join(missing))
    lines = [BASE_CSS]
    for name in ICONS:
        b64 = base64.b64encode(got[name].encode('utf-8')).decode('ascii')
        lines.append('.ic-%s{--ic:url("data:image/svg+xml;base64,%s");background-color:currentColor}'
                     % (name, b64))
    css = '\n'.join(lines) + '\n'
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(css)
    print('wrote %s  (%d icons, %.1f KB)' % (OUT, len(ICONS), len(css) / 1024))


if __name__ == '__main__':
    main()
