# Generated by Django 4.2.7 on 2026-06-15 10:29

from django.db import migrations


def seed_stock_available(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    content_type, _ = ContentType.objects.get_or_create(
        app_label='inventory',
        model='inventorypermission',
    )
    perm, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename='view_stock_available',
        defaults={'name': 'Can view stock available'},
    )

    # Dedicated group for people who should see ONLY the Stock Available page.
    stock_viewer, _ = Group.objects.get_or_create(name='stock_viewer')
    stock_viewer.permissions.add(perm)

    # Full inventory roles get the page too.
    for name in ('inventory_admin', 'inventory_viewer'):
        try:
            Group.objects.get(name=name).permissions.add(perm)
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_inventory_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorypermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_inventory', 'Can view inventory dashboard'), ('manage_inventory', 'Can manage inventory dashboard'), ('view_stock_available', 'Can view stock available')), 'verbose_name': 'inventory permission', 'verbose_name_plural': 'inventory permissions'},
        ),
        migrations.RunPython(seed_stock_available, migrations.RunPython.noop),
    ]
