# Generated by Django 6.0.5 on 2026-05-07 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('tgt_ltrs', models.FloatField(default=0)),
                ('tgt_rate', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realise_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'product_type', 'sub_group'],
                'indexes': [models.Index(fields=['year', 'month'], name='realise_mon_year_76f6cd_idx'), models.Index(fields=['product_type', 'sub_group'], name='realise_mon_product_a815aa_idx')],
                'unique_together': {('product_type', 'sub_group', 'month', 'year')},
            },
        ),
    ]
