# Generated by Django 5.2.14 on 2026-06-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True)),
                ('target_ltrs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realise.maingroupmaster')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realise.statemaster')),
            ],
            options={
                'ordering': ['-year', '-month', 'main_group__name', 'state__name', 'sales_person'],
                'indexes': [models.Index(fields=['year', 'month'], name='realise_tar_year_edbed4_idx'), models.Index(fields=['main_group'], name='realise_tar_main_gr_ad7d59_idx')],
                'unique_together': {('main_group', 'state', 'sales_person', 'month', 'year')},
            },
        ),
    ]
