# Generated by Django 5.2.14 on 2026-06-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0003_maingroupmaster_statemaster_targetmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('main_group', 'Main Group'), ('state', 'State'), ('person', 'Person')], max_length=20)),
                ('segment_value', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_realise_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['segment_type', 'segment_value'],
                'indexes': [models.Index(fields=['segment_type', 'year', 'month'], name='realise_seg_segment_e01115_idx')],
                'unique_together': {('segment_type', 'segment_value', 'month', 'year')},
            },
        ),
    ]
