# Generated by Django 5.2.14 on 2026-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0004_segmenttarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttarget',
            name='segment_type',
            field=models.CharField(choices=[('main_group', 'Main Group'), ('state', 'State'), ('person', 'Person'), ('premium_item', 'Premium Items'), ('commodity_item', 'Commodity Items')], max_length=20),
        ),
        migrations.CreateModel(
            name='TargetNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_group', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['main_group', 'state', 'sales_person'],
                'indexes': [models.Index(fields=['year', 'month'], name='realise_tar_year_2a271a_idx')],
                'unique_together': {('main_group', 'state', 'sales_person', 'month', 'year')},
            },
        ),
    ]
