# Generated by Django 4.2.7 on 2026-06-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0005_alter_segmenttarget_segment_type_targetnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetnode',
            name='target_realise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
