# Generated by Django 4.2.7 on 2026-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0006_targetnode_target_realise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetnode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='targetnode',
            name='segment',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='targetnode',
            unique_together={('main_group', 'state', 'sales_person', 'segment', 'month', 'year')},
        ),
    ]
