# Generated by Django 5.2.15 on 2026-06-17 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0007_alter_targetnode_unique_together_targetnode_segment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name'],
                'indexes': [models.Index(fields=['channel'], name='realise_ter_channel_9d56aa_idx')],
                'unique_together': {('channel', 'state_name')},
            },
        ),
    ]
