# Generated by Django 5.2.15 on 2026-06-18 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0008_territorymapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryProductTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('target_realise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_product_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name', 'product_type', 'sub_group'],
                'indexes': [models.Index(fields=['year', 'month'], name='realise_ter_year_7a5459_idx'), models.Index(fields=['channel', 'state_name'], name='realise_ter_channel_a83a47_idx')],
                'unique_together': {('channel', 'state_name', 'product_type', 'sub_group', 'month', 'year')},
            },
        ),
    ]
