# Generated by Django 5.2.15 on 2026-06-20 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0010_territoryproducttarget_sales_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name', 'city'],
                'indexes': [models.Index(fields=['channel', 'state_name'], name='realise_cit_channel_46a8c9_idx')],
                'unique_together': {('channel', 'state_name', 'city')},
            },
        ),
    ]
