# Generated by Django 4.2.7 on 2026-06-25 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Dedicated viewer group for the Required Credit Limit tab (mirrors the other report-tab
# groups in 0012). The can_required_credit_limit flag in core.context_processors checks it.
REQUIRED_CREDIT_GROUP = 'required_credit_viewer'


def create_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=REQUIRED_CREDIT_GROUP)


def remove_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=REQUIRED_CREDIT_GROUP).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realise', '0012_report_tab_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50, unique=True)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_group, remove_group),
    ]
