# Generated by Django 4.2.7 on 2026-06-26 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realise', '0013_closingremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lock_until', models.DateField()),
                ('days', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(max_length=160)),
                ('card_code', models.CharField(max_length=50)),
                ('outstanding', models.FloatField(default=0.0)),
                ('required_limit', models.FloatField(default=0.0)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='realise.creditlock')),
            ],
            options={
                'indexes': [models.Index(fields=['lock', 'row_key'], name='realise_cre_lock_id_c1c4ce_idx')],
            },
        ),
    ]
