# Generated by Django 4.2.7 on 2026-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0014_creditlock_creditlocksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('row_key', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['segment', 'year', 'month'], name='realise_fle_segment_ea497b_idx')],
                'unique_together': {('segment', 'year', 'month', 'row_key')},
            },
        ),
    ]
