# Generated by Django 4.2.7 on 2026-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0015_flextarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('row_key', models.CharField(max_length=80)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['card_code'], name='realise_agi_card_co_3ef4e1_idx')],
                'unique_together': {('card_code', 'row_key')},
            },
        ),
    ]
