# Generated by Django 5.2.14 on 2026-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0016_agingremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingRemarkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('row_key', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['card_code', 'row_key'], name='realise_agi_card_co_ce4e57_idx')],
            },
        ),
    ]
