# Generated by Django 4.2.7 on 2026-07-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realise', '0018_agingdueconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField()),
                ('party_code', models.CharField(blank=True, default='', max_length=50)),
                ('party_name', models.CharField(max_length=200)),
                ('main_group', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=200)),
                ('claim_type', models.CharField(blank=True, default='', max_length=120)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('claim_pass_date', models.DateField(blank=True, null=True)),
                ('claim_hold', models.CharField(blank=True, default='', max_length=10)),
                ('claim_passed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('hold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reason_of_hold', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claim_date', '-id'],
                'indexes': [models.Index(fields=['claim_date'], name='realise_cla_claim_d_9a8b87_idx'), models.Index(fields=['party_code'], name='realise_cla_party_c_c7d7c4_idx')],
            },
        ),
    ]
