# Generated by Django 5.2.14 on 2026-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0019_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_month',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
