# Generated by Django 5.2.14 on 2026-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0020_claim_claim_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='coop_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='ref_inv_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
