# Generated by Django 5.2.15 on 2026-07-18 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0024_realise_calculator_viewer_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(default='BOTH', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
