# Generated by Django 5.2.15 on 2026-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0025_ratelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelist',
            name='channel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
