# Generated by Django 5.2.15 on 2026-08-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0026_ratelist_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryItemTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('retailer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('box_litres', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pcs_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dm_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('disc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('target_realise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_item_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name', 'product_type', 'sub_group', 'item_code'],
                'indexes': [models.Index(fields=['year', 'month'], name='realise_ter_year_29eb31_idx'), models.Index(fields=['channel', 'state_name'], name='realise_ter_channel_28a481_idx'), models.Index(fields=['item_code'], name='realise_ter_item_co_829905_idx')],
                'unique_together': {('channel', 'state_name', 'item_code', 'month', 'year')},
            },
        ),
    ]
