# Generated by Django 5.2.15 on 2026-08-12 12:03

from django.db import migrations, models
from django.utils import timezone


def backfill_month(apps, schema_editor):
    """Stamp every existing plan with the month it was saved in.

    Leaving them blank would keep the bug this field fixes: a plan with no month shows in
    every month, so a July view would still carry August's plan. created_at is the best
    evidence we have of what a plan was for, and it is right for every row in practice —
    people build a month's rate list during that month.
    """
    RateList = apps.get_model('realise', 'RateList')
    for r in RateList.objects.filter(month='').only('id', 'created_at'):
        dt = r.created_at
        if not dt:
            continue
        if timezone.is_aware(dt):
            dt = timezone.localtime(dt)
        RateList.objects.filter(pk=r.pk).update(month=f'{dt.year:04d}-{dt.month:02d}')


def clear_month(apps, schema_editor):
    apps.get_model('realise', 'RateList').objects.update(month='')


class Migration(migrations.Migration):

    dependencies = [
        ('realise', '0027_territoryitemtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelist',
            name='month',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.RunPython(backfill_month, clear_month),
    ]
