name: Control Panel Test CI with Floci and Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-ci:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_S3_ENDPOINT_URL: http://localhost:4566
      DJANGO_SETTINGS_MODULE: control_panel.settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Floci
        run: |
          curl -fsSL https://floci.io/install.sh | sh
          echo "$HOME/.floci/bin" >> $GITHUB_PATH

      - name: Start Floci
        run: |
          floci start
          sleep 20

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply Test Infra
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Django requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Run tests
        run: python manage.py test